name: Build and release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BINARY_NAME: pomodorox

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: | 
        go build -o "$BINARY_NAME" main.go
        chmod +x $BINARY_NAME
    - name: Release Notes
      run: git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        body_path: ".github/RELEASE-TEMPLATE.md"
        draft: true
        files: pomodorox
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
